spring.application.name=medbooking
server.port=8082
spring.profiles.active=local

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/MedicalBookingDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=meduser
spring.datasource.password=medpass123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect