spring.application.name=medbooking

# Server Port Configuration (Backend running on 8082)
server.port=8082

# Activate Local Profile (loads application-local.properties)
spring.profiles.active=local

# Database Connection Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/MedicalBookingDB?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
